#!/bin/bash
kubectl apply -f secrets.yaml

istioctl kube-inject --injectConfigFile inject-config.yaml --valuesFile inject-values.yaml --filename bookinfo.yaml | kubectl apply -f -

kubectl apply -f gateway.yaml
