{
  "global": {
    "arch": {
      "amd64": 2,
      "ppc64le": 2,
      "s390x": 2
    },
    "caAddress": "",
    "configValidation": true,
    "defaultNodeSelector": {},
    "defaultPodDisruptionBudget": {
      "enabled": true
    },
    "defaultResources": {
      "requests": {
        "cpu": "10m"
      }
    },
    "enabled": true,
    "externalIstiod": false,
    "hub": "gcr.io/istio-release",
    "imagePullPolicy": "",
    "imagePullSecrets": [],
    "istioNamespace": "istio-system",
    "istiod": {
      "enableAnalysis": false
    },
    "jwtPolicy": "third-party-jwt",
    "logAsJson": false,
    "logging": {
      "level": "default:info"
    },
    "meshID": "",
    "meshNetworks": {},
    "mountMtlsCerts": true,
    # file mounted should be true but using provCert until we figure out how to make ADS work with k8s jwt
    # current error: 	ads	Failed to authenticate client from 10.1.119.134:59230: Authenticator ClientCertAuthenticator: no verified chain is found; Authenticator KubeJWTAuthenticator: target JWT extraction error: no HTTP authorization header exists
    "fileMountedCerts": false,
    "provCert": "/etc/certs",
    "pilotCertProvider": "custom",
    "multiCluster": {
      "clusterName": "",
      "enabled": false
    },
    "namespace": "istio-system",
    "network": "",
    "omitSidecarInjectorConfigMap": false,
    "oneNamespace": false,
    "operatorManageWebhooks": false,    
    "priorityClassName": "",
    "proxy": {
      "autoInject": "enabled",
      "clusterDomain": "cluster.local",
      "componentLogLevel": "misc:info",
      "enableCoreDump": false,
      "excludeIPRanges": "",
      "excludeInboundPorts": "",
      "excludeOutboundPorts": "",
      "holdApplicationUntilProxyStarts": false,
      "image": "proxyv2",
      "includeIPRanges": "*",
      "logLevel": "info",
      "privileged": false,
      "readinessFailureThreshold": 30,
      "readinessInitialDelaySeconds": 1,
      "readinessPeriodSeconds": 2,
      "resources": {
        "limits": {
          "cpu": "2000m",
          "memory": "1024Mi"
        },
        "requests": {
          "cpu": "100m",
          "memory": "128Mi"
        }
      },
      "statusPort": 15020,
      "tracer": "zipkin"
    },
    "proxy_init": {
      "image": "proxyv2",
      "resources": {
        "limits": {
          "cpu": "2000m",
          "memory": "1024Mi"
        },
        "requests": {
          "cpu": "10m",
          "memory": "10Mi"
        }
      }
    },
    "remotePilotAddress": "",
    "sds": {
      "token": {
        "aud": "istio-ca"
      }
    },
    "sts": {
      "servicePort": 0
    },
    "tag": "1.9.1",
    "tracer": {
      "datadog": {
        "address": "$(HOST_IP):8126"
      },
      "lightstep": {
        "accessToken": "",
        "address": ""
      },
      "stackdriver": {
        "debug": false,
        "maxNumberOfAnnotations": 200,
        "maxNumberOfAttributes": 200,
        "maxNumberOfMessageEvents": 200
      },
      "zipkin": {
        "address": ""
      }
    },
    "trustDomain": "",
    "useMCP": false
  },
  "istio_cni": {
    "enabled": false
  },
  "revision": "",
  "sidecarInjectorWebhook": {
    "alwaysInjectSelector": [],
    "defaultTemplates": [],
    "enableNamespacesByDefault": false,
    "injectedAnnotations": {},
    "neverInjectSelector": [],
    "objectSelector": {
      "autoInject": true,
      "enabled": true
    },
    "rewriteAppHTTPProbe": true,
    "templates": {},
    "useLegacySelectors": true
  }
}