FROM ubuntu:latest

RUN apt-get update
RUN apt-get -y install git
RUN apt-get -y install make
RUN apt-get -y install docker.io
RUN apt-get -y install ruby ruby-dev rubygems build-essential
RUN apt-get -y install rpm
RUN gem install --no-document fpm
RUN curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
RUN install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
RUN go get sigs.k8s.io/kind@v0.10.0
