apiVersion: v1
kind: ConfigMap
metadata:
  name: k8s-workload-registrar
  namespace: spire
data:
  k8s-workload-registrar.conf: |
    trust_domain = "example.org"
    server_socket_path = "/tmp/spire-server/private/api.sock"
    cluster = "demo-cluster"
    mode = "crd"
    pod_annotation = "spiffe.io/spiffe-id"
    metrics_bind_addr = "0"

