generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: spire-controller-manager-config
    namespace: spire
    files:
      - spire-controller-manager-config.yaml

resources:
- spire-namespace.yaml
- spiffe-csi-driver.yaml
- crd/spire.spiffe.io-clusterfederatedtrustdomains.yaml
- crd/spire.spiffe.io-clusterspiffeids.yaml
- crd-rbac/role.yaml
- crd-rbac/role-binding.yaml
- crd-rbac/leader-election-role.yaml
- crd-rbac/leader-election-role-binding.yaml
- spire-server.yaml
- spire-agent.yaml
- spire-controller-manager-webhook.yaml
