generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: spire-controller-manager-config
    namespace: spire
    files:
      - spire-controller-manager-config.yaml

resources:
- spire-namespace.yaml
- spiffe-csi-driver.yaml
- crd/spire.spiffe.io_clusterfederatedtrustdomains.yaml
- crd/spire.spiffe.io_clusterspiffeids.yaml
- crd-rbac/role.yaml
- crd-rbac/role_binding.yaml
- crd-rbac/leader_election_role.yaml
- crd-rbac/leader_election_role_binding.yaml
- spire-server.yaml
- spire-agent.yaml
- spire-controller-manager-webhook.yaml
