apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: spire

resources:
  - spiffe-csi-driver.yaml
  - k8s-workload-registrar-crd-cluster-role.yaml
  - k8s-workload-registrar-crd-configmap.yaml
  - spiffeid.spiffe.io_spiffeids.yaml
  - server-account.yaml
  - spire-bundle-configmap.yaml
  - server-cluster-role.yaml
  - server-configmap.yaml
  - server-statefulset.yaml
  - server-service.yaml
  - agent-account.yaml
  - agent-cluster-role.yaml
  - agent-configmap.yaml
  - agent-daemonset.yaml
