apiVersion: v1
kind: ConfigMap
metadata:
  name: spire-agent-nest
  namespace: spire
data:
  agent.conf: |
    agent {
      data_dir = "/run/spire"
      log_level = "DEBUG"
      server_address = "root-spire"
      server_port = "8081"
      socket_path = "/tmp/agent-nestedA.sock"
      trust_bundle_path = "/run/spire/upstream/root-cert.pem"
      trust_domain = "example.org"
    }

    plugins {

      NodeAttestor "x509pop" {
          plugin_data {
              private_key_path = "/run/spire/upstream/agent-nestedA.key.pem"
              certificate_path = "/run/spire/upstream/agent-nestedA.crt.pem"
          }
      }

      KeyManager "memory" {
        plugin_data {
        }
      }

      WorkloadAttestor "unix" {
          plugin_data {
          }
      }
    }

    health_checks {
      listener_enabled = true
      bind_address = "0.0.0.0"
      bind_port = "8082"
      live_path = "/live"
      ready_path = "/ready"
    }
