apiVersion: v1
kind: Service
metadata:
  name: bundle-endpoint
  namespace: spire2
spec:
  type: NodePort
  ports:
    - name: http
      port: 8443
      targetPort: 8443
      protocol: TCP
  selector:
    app: spire-server
