# Bundle set by synchronizer
apiVersion: v1
kind: ConfigMap
metadata:
  name: trust-bundle
  namespace: default
---
# This remains empty but needs to be present
apiVersion: v1
kind: ConfigMap
metadata:
  name: istio-ca-root-cert
  namespace: default
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: spiffe-helper-config
  namespace: default
data:
  helper.conf: |
    agentAddress = "/run/spire/sockets/agent.sock"
    # sh binay
    cmd = "sh"
    # Command to change certificate permissions after rotation
    cmdArgs = "-c \"chmod 644 /sleep-certs/* && chmod 600 /sleep-certs/sleep-key.pem\" "
    # Directory to store certificates
    certDir = "/sleep-certs"
    # Certificate, key and bundle files
    svidFileName = "sleep-svid.pem"
    svidKeyFileName = "sleep-key.pem"
    svidBundleFileName = "root-cert.pem"