apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
spec:
  profile: default
  meshConfig:
    trustDomain: {{ .Values.trustDomain }}
  values:
    global:
      hub: {{ .Values.hub }}
      tag: {{ .Values.tag }}
      imagePullPolicy: "IfNotPresent"
      imagePullSecrets:
        - secret-registry
    # This is used to customize the sidecar template
    sidecarInjectorWebhook:
      templates:
        spire: |
          spec:
            containers:
            - name: istio-proxy
            volumes:
            - name: workload-socket
              csi:
                driver: "csi.spiffe.io"
  components:
    pilot:
      k8s:
        env:
          - name: ENABLE_CA_SERVER
            value: "true"
          - name: PILOT_ENABLE_XDS_IDENTITY_CHECK
            value: "true"
        overlays:
          - apiVersion: apps/v1
            kind: Deployment
            name: istiod
            patches:
              - path: spec.template.metadata.labels.spireSpiffeid
                value: istiod
    ingressGateways:
      - name: istio-ingressgateway
        enabled: true
        label:
          istio: ingressgateway
          spireSpiffeid: ingress
        k8s:
          overlays:
            - apiVersion: apps/v1
              kind: Deployment
              name: istio-ingressgateway
              patches:
                - path: spec.template.spec.volumes.[name:workload-socket]
                  value:
                    name: workload-socket
                    csi:
                      driver: "csi.spiffe.io"
