# Bundle set by trust bundle synchronizer
apiVersion: v1
kind: ConfigMap
metadata:
  name: trust-bundle
  namespace: istio-system
---
# This remains empty but needs to be present because of istio-agent injection
apiVersion: v1
kind: ConfigMap
metadata:
  name: istio-ca-root-cert
  namespace: istio-system
---
