apiVersion: v1
entries:
  base:
  - apiVersion: v1
    appVersion: 1.14.1
    created: "2022-07-29T17:00:00.186966334-03:00"
    description: Helm chart for deploying Istio cluster resources and CRDs
    digest: e495c399488844c5f34330044564b6e2f575c736afacf2959cfd913bfc00116e
    icon: https://istio.io/latest/favicons/android-192x192.png
    keywords:
    - istio
    name: base
    sources:
    - http://github.com/istio/istio
    urls:
    - https://hewlettpackard.github.io/Mithril/mithrilctl/helm/mithril/base-1.14.1.tgz
    version: 1.14.1
  gateway:
  - apiVersion: v2
    appVersion: 1.14.1
    created: "2022-07-29T17:00:00.187666127-03:00"
    description: Helm chart for deploying Istio gateways
    digest: 3a90133a08f7e8ed31f1f1d53a7372775a7274516f3282affc046140501dd67b
    icon: https://istio.io/latest/favicons/android-192x192.png
    keywords:
    - istio
    - gateways
    name: gateway
    sources:
    - http://github.com/istio/istio
    type: application
    urls:
    - https://hewlettpackard.github.io/Mithril/mithrilctl/helm/mithril/gateway-1.14.1.tgz
    version: 1.14.1
  istiod:
  - apiVersion: v1
    appVersion: 1.14.1
    created: "2022-07-29T17:00:00.190199858-03:00"
    description: Helm chart for istio control plane
    digest: 8fc3eb1e1e45fbc6781f5800498f78bf7b32e257f7fa187a0539c3d2126943f7
    icon: https://istio.io/latest/favicons/android-192x192.png
    keywords:
    - istio
    - istiod
    - istio-discovery
    name: istiod
    sources:
    - http://github.com/istio/istio
    urls:
    - https://hewlettpackard.github.io/Mithril/mithrilctl/helm/mithril/istiod-1.14.1.tgz
    version: 1.14.1
  spire-agent:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2022-07-29T17:00:00.190561642-03:00"
    description: A Helm chart for Kubernetes
    digest: 8db024657c3a38018d3598f6c1ef8e660253abaafbec2576747975b37baa989d
    name: spire-agent
    type: application
    urls:
    - https://hewlettpackard.github.io/Mithril/mithrilctl/helm/mithril/spire-agent-1.3.2.tgz
    version: 1.3.2
  spire-server:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2022-07-29T17:00:00.191177647-03:00"
    description: A Helm chart for Kubernetes
    digest: ce4e07176ca0e5e24d8dc96c9f02c427cd35ebdf62bff13b729b6323c2c08cfb
    name: spire-server
    type: application
    urls:
    - https://hewlettpackard.github.io/Mithril/mithrilctl/helm/mithril/spire-server-1.3.2.tgz
    version: 1.3.2
generated: "2022-07-29T17:00:00.184576094-03:00"
