# Default values for spire-server.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
namespace: spire
name: spire-server
trustDomain: "example.org"
clusterName: demo-cluster
image: spire-server:1.3.2
controllerManagerImage: spire-controller-manager:0.2.1

configmaps:
  notifier:
    bundleName: trust-bundle
  serverConfig:
    socketPath: "/run/spire/sockets/api.sock"
    trustDomain: "example.org"
    federates: false
    logLevel: DEBUG
    federation:
        bundleEndpoint:
          address: 0.0.0.0
          port: 8443
        federations:
          - federatesWith: "domain.test"
            bundleEndpointUrl: https://192.168.0.16:4002
            bundleEndpointProfile:
              profile: https_spiffe
              endpointSpiffeId: spiffe://domain.test/spire/server
    ttl: "1h"
    notifier:
      configMap: "trust-bundle"
      configMapKey: "root-cert.pem"

replicaCount: 1

serviceSpire:
  type: NodePort
  ports:
   - name: api
     port: 8081
     targetPort: 8081
     protocol: TCP

serviceBundleEndpoint:
  name: spire-server-bundle-endpoint
  type: NodePort
  ports:
    - name: api
      port: 8443
      protocol: TCP

serviceControllerWebhook:
  name: spire-controller-manager-webhook-service
  type: NodePort
  ports:
    - port: 443
      protocol: TCP
      targetPort: 9443

volumeClaimTemplates:
  storage: 1Gi
