apiVersion: spire.spiffe.io/v1alpha1
kind: ClusterSPIFFEID
metadata:
  name: greeter-server
spec:
  spiffeIDTemplate: spiffe://cluster1.demo/greeter-server
  podSelector:
    matchLabels:
      spire.spiffe.io/spiffeid: greeter-server
  federatesWith: ["cluster2.demo"]
