apiVersion: spire.spiffe.io/v1alpha1
kind: ClusterSPIFFEID
metadata:
  name: istiod
spec:
  spiffeIDTemplate: spiffe://example.org/istiod/{{ .PodMeta.Name }}
  dnsNameTemplates:
    - istiod.istio-system.svc
  podSelector:
    matchLabels:
      spire.spiffe.io/spiffeid: istiod
---
apiVersion: spire.spiffe.io/v1alpha1
kind: ClusterSPIFFEID
metadata:
  name: ingress
spec:
  spiffeIDTemplate: spiffe://example.org/ns/ingress/{{ .PodMeta.Name }}
  podSelector:
    matchLabels:
      spire.spiffe.io/spiffeid: ingress
#  federatesWith: ["cluster2.demo"]
---
apiVersion: spire.spiffe.io/v1alpha1
kind: ClusterSPIFFEID
metadata:
  name: workloads
spec:
  spiffeIDTemplate: spiffe://example.org/{{ .PodMeta.Name }}
  podSelector:
    matchLabels:
      spire.spiffe.io/spiffeid: workloads
#  federatesWith: ["cluster2.demo"]

