apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: spire-server
  namespace: spire
  labels:
    app: spire-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spire-server
  serviceName: spire-server
  template:
    metadata:
      namespace: spire
      labels:
        app: spire-server
    spec:
      serviceAccountName: spire-server
      hostPID: true
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      hostAliases:
        - ip: "10.0.1.50"  # Endpoint of the Root SPIRE Server
          hostnames:
            - "root-spire"
      containers:
        - name: spire-server
          image: gcr.io/spiffe-io/spire-server:1.0.0
          args:
            - -config
            - /run/spire/config/server.conf
          livenessProbe:
            httpGet:
              path: /live
              port: 8080
            failureThreshold: 2
            initialDelaySeconds: 15
            periodSeconds: 60
            timeoutSeconds: 3
          readinessProbe:
            httpGet:
              path: /ready
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
          ports:
            - containerPort: 8081
          volumeMounts:
            - name: spire-config
              mountPath: /run/spire/config
              readOnly: true
            - name: spire-data
              mountPath: /run/spire/data
              readOnly: false
            - name: spire-registration-socket
              mountPath: /run/spire/sockets
              readOnly: false
            - name: tmp
              mountPath: /tmp
        - name: k8s-workload-registrar
          image: gcr.io/spiffe-io/k8s-workload-registrar:1.0.0
          args:
            - -config
            - /run/spire/config/k8s-workload-registrar.conf
          ports:
            - containerPort: 9443
              name: webhook
              protocol: TCP
          volumeMounts:
            - mountPath: /run/spire/config
              name: k8s-workload-registrar-config
              readOnly: true
            - name: spire-registration-socket
              mountPath: /run/spire/sockets
              readOnly: true
        - name: spire-agent-nest
          image: gcr.io/spiffe-io/spire-agent:1.0.0
          args: ["-config", "/run/spire/config/agent.conf"]
          volumeMounts:
            - name: spire-config-nest
              mountPath: /run/spire/config
              readOnly: true
            - name: spire-token
              mountPath: /var/run/secrets/tokens
            - name: spire-bundle-nest
              mountPath: /run/spire/upstream/root-cert.pem
              subPath: root-cert.pem
              readOnly: true
            - name: agent-nestedb-cert
              mountPath: /run/spire/upstream/agent-nestedB.crt.pem
              subPath: agent-nestedB.crt.pem
              readOnly: true
            - name: agent-nestedb-key
              mountPath: /run/spire/upstream/agent-nestedB.key.pem
              subPath: agent-nestedB.key.pem
              readOnly: true
            - name: tmp
              mountPath: /tmp
          livenessProbe:
            httpGet:
              path: /live
              port: 8082
            failureThreshold: 2
            initialDelaySeconds: 15
            periodSeconds: 60
            timeoutSeconds: 3
          readinessProbe:
            httpGet:
              path: /ready
              port: 8082
            initialDelaySeconds: 5
            periodSeconds: 5
      volumes:
        - name: spire-config
          configMap:
            name: spire-server
        - name: k8s-workload-registrar-config
          configMap:
            name: k8s-workload-registrar
        - name: spire-registration-socket
          hostPath:
            path: /run/spire/server-sockets
            type: DirectoryOrCreate
        - name: spire-token
          projected:
            sources:
              - serviceAccountToken:
                  path: spire-agent-nest
                  expirationSeconds: 7200
                  audience: spire-server
        - name: spire-config-nest
          configMap:
            name: spire-agent-nest
        - name: spire-bundle-nest
          configMap:
            name: spire-bundle-nest
        - name: agent-nestedb-cert
          configMap:
            name: agent-nestedb-cert
        - name: agent-nestedb-key
          configMap:
            name: agent-nestedb-key
        - name: tmp
          emptyDir: {}
  volumeClaimTemplates:
    - metadata:
        name: spire-data
        namespace: spire
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
