# TODO: Add explanation
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: prow
  name: config
data:
  config.yaml: |
    prowjob_namespace: prow
    pod_namespace: test-pods-3 #TODO: Change to name of pod_namespace

    in_repo_config:
      enabled:
        "*": true

    deck:
      spyglass:
        lenses:
        - lens:
            name: metadata
          required_files:
          - started.json|finished.json
        - lens:
            config:
            name: buildlog
          required_files:
          - build-log.txt
        - lens:
            name: junit
          required_files:
          - .*/junit.xml
        - lens:
            name: podinfo
          required_files:
          - podinfo.json
      branding:
        header_color: '#404b5c'
        logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/46/Hewlett_Packard_Enterprise_logo.svg/400px-Hewlett_Packard_Enterprise_logo.svg.png'

    plank:
      job_url_prefix_config:
        "*": https://prow.spire-test.com/view/
      report_templates:
        '*': >-
            [Full PR test history](https://prow.spire-test.com/pr-history?org={{.Spec.Refs.Org}}&repo={{.Spec.Refs.Repo}}&pr={{with index .Spec.Refs.Pulls 0}}{{.Number}}{{end}}).
            [Your PR dashboard](https://prow.spire-test.com/pr?query=is:pr+state:open+author:{{with
            index .Spec.Refs.Pulls 0}}{{.Author}}{{end}}).
      default_decoration_configs:
        "*":
          gcs_configuration:
            bucket: s3://prow-logs
            path_strategy: explicit
          s3_credentials_secret: s3-credentials
          utility_images:
            clonerefs: gcr.io/k8s-prow/clonerefs:v20211210-dfd4c4dd7d
            entrypoint: gcr.io/k8s-prow/entrypoint:v20211210-dfd4c4dd7d
            initupload: gcr.io/k8s-prow/initupload:v20211210-dfd4c4dd7d
            sidecar: gcr.io/k8s-prow/sidecar:v20211210-dfd4c4dd7d

    sinker:
      max_pod_age: 10m
      max_prowjob_age: 24h
      resync_period: 300m

    tide:
      queries:
      - repos:
        - HewlettPackard/Mithril
        labels:
        - nao-aprova-nao
        missingLabels:
        - do-not-merge
        - do-not-merge/hold
        - do-not-merge/work-in-progress
        - needs-ok-to-test
        - needs-rebase

    decorate_all_jobs: true
    periodics:

    #TODO: replicate for different tags and go versions
    - interval: 100m
      agent: kubernetes
      name: istio-unit-test
      spec:
        imagePullSecrets:
        - name: secret-registry
        containers:
        - image: "529024819027.dkr.ecr.us-east-1.amazonaws.com/mithril:04-01-2022-release-1.12-master-a04a4e6"
          command: ["/bin/bash", "/mithril/prow-files/istio-unit-tests.sh"]
          envFrom:
          - secretRef:
              name: aws-secret
          volumeMounts:
          - name: config-volume
            mountPath: /mithril/prow-files
        volumes:
          - name: config-volume
            configMap:
              name: prow-files

    - interval: 24h
      agent: kubernetes
      decorate: true
      # decoration_config:
      #   ssh_key_secrets:
      #   - ssh-key-secret
      # extra_refs:
      #   - org: HewlettPackard
      #     clone_uri: "git@github.com:HewlettPackard/prow.git"
      #     repo: prow
      #     base_ref: initial
      name: create-istio-images-and-push-ecr
      spec:
        imagePullSecrets:
        - name: secret-registry
        containers:
        - image: "529024819027.dkr.ecr.us-east-1.amazonaws.com/mithril:04-01-2022-release-1.12-master-a04a4e6"
          command: ["/bin/bash", "/mithril/prow-files/istio-images.sh"]
          envFrom:
          - secretRef:
              name: aws-secret
          securityContext:
            privileged: true
          volumeMounts:
          - name: config-volume
            mountPath: /mithril/prow-files
        volumes:
          - name: config-volume
            configMap:
              name: prow-files

    #depends on create-istio-images-and-push-ecr
    - interval: 24h
      agent: kubernetes
      name: tag-latest
      spec:
        imagePullSecrets:
        - name: secret-registry
        containers:
        - image: "529024819027.dkr.ecr.us-east-1.amazonaws.com/mithril:04-01-2022-release-1.12-master-a04a4e6"
          command: ["/bin/bash", "/mithril/prow-files/tag-latest-images.sh"]
          envFrom:
          - secretRef:
              name: aws-secret
          securityContext:
            privileged: true
          volumeMounts:
          - name: config-volume
            mountPath: /mithril/prow-files
        volumes:
          - name: config-volume
            configMap:
              name: prow-files

    #postsubmit
    - interval: 24h
      agent: kubernetes
      name: distribute-patches
      spec:
        imagePullSecrets:
        - name: secret-registry
        containers:
        - image: "529024819027.dkr.ecr.us-east-1.amazonaws.com/mithril:04-01-2022-release-1.12-master-a04a4e6"
          command: ["/bin/sh", "/mithril/prow-files/distribute-patches.sh"]
          envFrom:
          - secretRef:
              name: aws-secret
          volumeMounts:
          - name: config-volume
            mountPath: /mithril/prow-files
        volumes:
          - name: config-volume
            configMap:
              name: prow-files

    #postsubmit
    - interval: 24h
      agent: kubernetes
      name: distribute-assets
      spec:
        imagePullSecrets:
        - name: secret-registry
        containers:
        - image: "529024819027.dkr.ecr.us-east-1.amazonaws.com/mithril:04-01-2022-release-1.12-master-a04a4e6"
          command: ["/bin/sh", "/mithril/prow-files/distribute-assets.sh"]
          envFrom:
          - secretRef:
              name: aws-secret
          volumeMounts:
          - name: config-volume
            mountPath: /mithril/prow-files
        volumes:
          - name: config-volume
            configMap:
              name: prow-files

    #presubmit
    - interval: 24h
      agent: kubernetes
      name: analyze-integration-tests
      spec:
        imagePullSecrets:
        - name: secret-registry
        containers:
        - image: "529024819027.dkr.ecr.us-east-1.amazonaws.com/mithril:04-01-2022-release-1.12-master-a04a4e6"
          command: ["/bin/bash", "/mithril/prow-files/analyze-integration-tests.sh"]
          envFrom:
          - secretRef:
              name: aws-secret
          volumeMounts:
          - name: config-volume
            mountPath: /mithril/prow-files
        volumes:
          - name: config-volume
            configMap:
              name: prow-files

    #presubmit
    - interval: 24h
      agent: kubernetes
      name: integration-tests
      spec:
        imagePullSecrets:
        - name: secret-registry
        containers:
        - image: "529024819027.dkr.ecr.us-east-1.amazonaws.com/mithril:04-01-2022-release-1.12-master-a04a4e6"
          command: ["/bin/bash", "/mithril/prow-files/integration-tests.sh"]
          envFrom:
          - secretRef:
              name: aws-secret
          volumeMounts:
          - name: config-volume
            mountPath: /mithril/prow-files
        volumes:
          - name: config-volume
            configMap:
              name: prow-files

    - interval: 100m
      agent: kubernetes
      decorate: true
      decoration_config:
        ssh_key_secrets:
        - ssh-key-secret
        extra_refs:
        - org: HewlettPackard
          repo: prow
          base_ref: main
          workdir: false
          clone_uri: "git@github.com:HewlettPackard/Mithril.git"
      name: ls-hpe
      spec:
        imagePullSecrets:
        - name: secret-registry
        containers:
        - image: "529024819027.dkr.ecr.us-east-1.amazonaws.com/mithril:04-01-2022-release-1.12-master-a04a4e6"
          command: ["/bin/bash", "-c", "ls"]

