apiVersion: v1
kind: ConfigMap
metadata:
  namespace: prow
  name: config
data:
  config.yaml: |
    prowjob_namespace: prow
    pod_namespace: test-pods-4 

    in_repo_config:
      enabled:
        "*": true

    deck:
      spyglass:
        lenses:
        - lens:
            name: metadata
          required_files:
          - started.json|finished.json
        - lens:
            config:
            name: buildlog
          required_files:
          - build-log.txt
        - lens:
            name: junit
          required_files:
          - .*/junit.xml
        - lens:
            name: podinfo
          required_files:
          - podinfo.json
      branding:
        header_color: '#404b5c'
        logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/46/Hewlett_Packard_Enterprise_logo.svg/400px-Hewlett_Packard_Enterprise_logo.svg.png'

    plank:
      job_url_prefix_config:
        "*": https://prow.spire-test.com/view/
      report_templates:
        '*': >-
            [Full PR test history](https://prow.spire-test.com/pr-history?org={{.Spec.Refs.Org}}&repo={{.Spec.Refs.Repo}}&pr={{with index .Spec.Refs.Pulls 0}}{{.Number}}{{end}}).
            [Your PR dashboard](https://prow.spire-test.com/pr?query=is:pr+state:open+author:{{with
            index .Spec.Refs.Pulls 0}}{{.Author}}{{end}}).
      default_decoration_configs:
        "*":
          gcs_configuration:
            bucket: s3://prow-logs
            path_strategy: explicit
          s3_credentials_secret: s3-credentials
          ssh_key_secrets:
            - ssh-secret
          utility_images:
            clonerefs: gcr.io/k8s-prow/clonerefs:v20211210-dfd4c4dd7d
            entrypoint: gcr.io/k8s-prow/entrypoint:v20211210-dfd4c4dd7d
            initupload: gcr.io/k8s-prow/initupload:v20211210-dfd4c4dd7d
            sidecar: gcr.io/k8s-prow/sidecar:v20211210-dfd4c4dd7d

    sinker:
      max_pod_age: 24h
      max_prowjob_age: 24h
      resync_period: 300m

    tide:
      queries:
      - repos:
        - HewlettPackard/Mithril
        labels:
        - nao-aprova-nao
        missingLabels:
        - do-not-merge
        - do-not-merge/hold
        - do-not-merge/work-in-progress
        - needs-ok-to-test
        - needs-rebase

    decorate_all_jobs: true
    periodics:
    - name: master-istio-unit-test
      interval: 24h
      agent: kubernetes
      decoration_config:
        ssh_key_secrets:
        - ssh-key-secret
      extra_refs:
      - org: HewlettPackard
        repo: Mithril
        base_ref: prow
        clone_uri: "git@github.com:HewlettPackard/Mithril.git"
      spec:
        imagePullSecrets:
        - name: secret-registry
        containers:
        - image: "529024819027.dkr.ecr.us-east-1.amazonaws.com/mithril-deps:latest"
          command: ["/bin/bash", "-c", "prow/prowjobs/istio-unit-tests.sh"]
          env:
          - name: BRANCH
            value: master

    - name: release-1.11-istio-unit-test
      interval: 24h
      agent: kubernetes
      decoration_config:
        ssh_key_secrets:
        - ssh-key-secret
      extra_refs:
      - org: HewlettPackard
        repo: Mithril
        base_ref: prow
        clone_uri: "git@github.com:HewlettPackard/Mithril.git"
      spec:
        imagePullSecrets:
        - name: secret-registry
        containers:
        - image: "529024819027.dkr.ecr.us-east-1.amazonaws.com/mithril-deps:latest"
          command: ["/bin/bash", "-c", "prow/prowjobs/istio-unit-tests.sh"]
          env:
          - name: BRANCH
            value: release-1.11

    - name: release-1.12-istio-unit-test
      interval: 24h
      agent: kubernetes
      decoration_config:
        ssh_key_secrets:
        - ssh-key-secret
      extra_refs:
      - org: HewlettPackard
        repo: Mithril
        base_ref: prow
        clone_uri: "git@github.com:HewlettPackard/Mithril.git"
      spec:
        imagePullSecrets:
        - name: secret-registry
        containers:
        - image: "529024819027.dkr.ecr.us-east-1.amazonaws.com/mithril-deps:latest"
          command: ["/bin/bash", "-c", "prow/prowjobs/istio-unit-tests.sh"]
          env:
          - name: BRANCH
            value: release-1.12
            
    - name: integ-pilot-istio
      interval: 5m
      agent: kubernetes
      decoration_config:
        ssh_key_secrets:
        - ssh-key-secret
      extra_refs:
      - org: HewlettPackard
        repo: istio
        base_ref: master
        clone_uri: "git@github.com:HewlettPackard/istio.git"
      spec:
        imagePullSecrets:
        - name: secret-registry
        securityContext:
          privileged: true
        containers:
        - image: "529024819027.dkr.ecr.us-east-1.amazonaws.com/mithril/prow:latest"
          command: ["/bin/bash", "-c", "sleep 2000"]
          env:
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: aws-secret
                  key: aws_access_key_id
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-secret
                  key: aws_secret_access_key
            - name: AWS_DEFAULT_REGION
              value: us-east-1
          volumeMounts:
            - name: docker-vol
              mountPath: /var/lib/docker
              readOnly: true
            - name: docker-sock
              mountPath: /var/run/docker.sock
              readOnly: true
            # - name: cgroup
            #   mountPath: /sys/fs/cgroup
            #   readOnly: true
            # - name: modules
            #   mountPath: /lib/modules
            #   readOnly: true
            - name: tf-vol
              mountPath: /terraform
        # hostNetwork: true
        volumes:  
        - name: docker-vol
          emptyDir: {}
        - name: docker-sock
          hostPath:
            path: /var/run/docker.sock
        - name: tf-vol
          configMap:
            name: tf-config
        # - name: modules
        #   hostPath:
        #     path: /lib/modules
        # - name: cgroup
        #   hostPath:
        #     path: /sys/fs/cgroup

    presubmits:
      HewlettPackard/Mithril:
      - name: date           
        decorate: true           
        always_run: true         
        skip_report: false        
        max_concurrency: 10     
        spec:
          containers:
          - image: alpine
            command: ["/bin/date"]
        branches: 
        - ^main$
        - ^prow$
        skip_branches:        
        - ^release-.*$
        trigger: "date" 
        rerun_command: "date"  

    # postsubmits:
    #   HewlettPackard/Mithril:
    #   - name: create-istio-images-and-push-ecr 
    #     branches:
    #     - main
    #     - prow
    #     always_run: true
    #     decorate: true
        # decoration_config:
        #   ssh_key_secrets:
        #   - ssh-key-secret
        # extra_refs:
        # - org: HewlettPackard
        #   repo: Mithril
        #   clone_uri: "git@github.com:HewlettPackard/Mithril.git"
        # spec:
        #   imagePullSecrets:
        #   - name: secret-registry
        #   containers:
        #   - image: "529024819027.dkr.ecr.us-east-1.amazonaws.com/mithril:04-01-2022-release-1.12-master-a04a4e6"
        #     command: ["/bin/bash", "prow/prowjobs/istio-images.sh"]
        #     envFrom:
        #     - secretRef:
        #         name: aws-secret
        #     securityContext:
        #       privileged: true
        
    postsubmits:
      HewlettPackard/Mithril:
      - name: ls
        branches:
        - main
        - prow
        always_run: true
        decorate: true
        clone_uri: "ssh://git@github.com/HewlettPackard/Mithril.git"
        spec:
          containers:
          - image: alpine
            command: ["sleep 240"]

    # - name: analyze-integration-tests
    #   agent: kubernetes
    #   decorate: true
    #   decoration_config:
    #     ssh_key_secrets:
    #     - ssh-key-secret
    #   extra_refs:
    #   - org: HewlettPackard
    #     repo: Mithril
    #     clone_uri: "git@github.com:HewlettPackard/Mithril.git"
    #   spec:
    #     imagePullSecrets:
    #     - name: secret-registry
    #     containers:
    #     - image: "529024819027.dkr.ecr.us-east-1.amazonaws.com/mithril-deps:latest"
    #       command: ["/bin/bash", "prow/prowjobs/analyze-integration-tests.sh"]
    #       envFrom:
    #       - secretRef:
    #           name: aws-secret

    # - name: integration-tests
    #   agent: kubernetes
    #   decorate: true
    #   decoration_config:
    #     ssh_key_secrets:
    #     - ssh-key-secret
    #   extra_refs:
    #   - org: HewlettPackard
    #     repo: Mithril
    #     clone_uri: "git@github.com:HewlettPackard/Mithril.git"
    #   spec:
    #     imagePullSecrets:
    #     - name: secret-registry
    #     containers:
    #     - image: "529024819027.dkr.ecr.us-east-1.amazonaws.com/mithril-deps:latest"
    #       command: ["/bin/bash", "prow/prowjobs/integration-tests.sh"]
    #       envFrom:
    #       - secretRef:
    #           name: aws-secret

    # postsubmits:
    # - name: distribute-patches
    #   agent: kubernetes
    #   decoration_config:
    #     ssh_key_secrets:
    #     - ssh-key-secret
    #   extra_refs:
    #   - org: HewlettPackard
    #     repo: Mithril
    #     clone_uri: "git@github.com:HewlettPackard/Mithril.git"
    #   spec:
    #     imagePullSecrets:
    #     - name: secret-registry
    #     containers:
    #     - image: "529024819027.dkr.ecr.us-east-1.amazonaws.com/mithril-deps:latest"
    #       command: ["/bin/sh", "prow/prowjobs/distribute-patches.sh"]
    #       envFrom:
    #       - secretRef:
    #           name: aws-secret

    # - name: distribute-assets
    #   agent: kubernetes
    #   decoration_config:
    #     ssh_key_secrets:
    #     - ssh-key-secret
    #   extra_refs:
    #   - org: HewlettPackard
    #     repo: Mithril
    #     clone_uri: "git@github.com:HewlettPackard/Mithril.git"
    #   spec:
    #     imagePullSecrets:
    #     - name: secret-registry
    #     containers:
    #     - image: "529024819027.dkr.ecr.us-east-1.amazonaws.com/mithril-deps:latest"
    #       command: ["/bin/sh", "prow/prowjobs/distribute-assets.sh"]
    #       envFrom:
    #       - secretRef:
    #           name: aws-secret

    # - name: tag-latest
    #   agent: kubernetes
    #   decoration_config:
    #     ssh_key_secrets:
    #     - ssh-key-secret
    #   extra_refs:
    #   - org: HewlettPackard
    #     repo: Mithril
    #     clone_uri: "git@github.com:HewlettPackard/Mithril.git"
    #   spec:
    #     imagePullSecrets:
    #     - name: secret-registry
    #     containers:
    #     - image: "529024819027.dkr.ecr.us-east-1.amazonaws.com/mithril-deps:latest"
    #       command: ["/bin/bash", "-c", "prow/prowjobs/tag-latest-images.sh"]
    #       envFrom:
    #       - secretRef:
    #           name: aws-secret
    #       securityContext:
    #         privileged: true
